interest Domain Adapter Service Handler Payload creat
intellibucket/be-on-network pull request #102
Opened 2024-03-04 23:21 UTC by royalhsyn

2024-03-05 20:48 UTC, l00pss requested changes
Coordinator ilə əlaqəli əlavələri silə bilərsiz. Şərhləri nəzərə alarsız zəhmət olmasa

2024-03-05 20:48 UTC, l00pss commented on job-seeker-service/js-application/js-presentation/src/main/java/az/rock/flyjob/js/presentation/api/rest/privates/command/resume/detail/InterestCommandPrivateController.java
>      public ResponseEntity<JSuccessResponse> create(CreateRequest<InterestCommandModel> request) {
@RequestBody əlavə olunmalıdır

2024-03-05 20:48 UTC, l00pss commented on job-seeker-service/js-domain/js-domain-presentation/src/main/java/az/rock/flyjob/js/domain/presentation/dto/request/item/InterestCommandModel.java
> +    public InterestCommandModel(Boolean isHobby, String name, String description) {
Request Modeller üçün set metodları yazmağınız yaxşıdır. Jackson versiyasına görə deserilization xətası ala bilərsiz

2024-03-05 20:48 UTC, l00pss commented on job-seeker-service/js-domain/js-domain-presentation/src/main/java/az/rock/flyjob/js/domain/presentation/handler/abstracts/AbstractInterestCreateCommandHandler.java
> +    InterestCreatedEvent add(InterestCommandModel interestCommandModel);
Method ismində standartı qorusaq yaxşıdır. create update merge delete kimi

2024-03-05 20:48 UTC, l00pss commented on job-seeker-service/js-domain/js-domain-presentation/src/main/java/az/rock/flyjob/js/domain/presentation/ports/input/services/command/abstracts/AbstractInterestCommandDomainPresentationService.java
> +    void createInterest(InterestCommandModel newInterestCommandModel);
Sinf adında domain haqqında məlumat olduğu üçün createİnterest yazmaq yerinə qısaca create yazmaq kafidi

2024-03-05 20:48 UTC, l00pss commented on job-seeker-service/js-domain/js-domain-presentation/src/main/java/az/rock/flyjob/js/domain/presentation/ports/input/services/command/concretes/InterestCommandDomainPresentationService.java
> +        var step = InterestRegistrationSteps.ON_STARTED_STEP;
Coordinator isdifadə edilməməlidir. Ehtiyac yoxdur.

2024-03-05 20:48 UTC, l00pss commented on job-seeker-service/js-domain/js-domain-presentation/src/main/java/az/rock/flyjob/js/domain/presentation/ports/output/publisher/AbstractInterestMessagePublisher.java
> +public interface AbstractInterestMessagePublisher<S extends AbstractDomainEvent> extends AbstractMessagePublisher<S> {
Ehtiyac yoxdur

2024-03-05 20:48 UTC, l00pss commented on job-seeker-service/js-domain/js-domain-presentation/src/main/java/az/rock/flyjob/js/domain/presentation/ports/output/repository/query/AbstractInterestQueryRepositoryAdapter.java
> +    Boolean isExistInterestName(InterestRoot interestRoot);
ResumeİD qəbul elemelidi method isExist yerinə qısaca existByResumeIDAndName

2024-03-05 20:48 UTC, l00pss commented on library/ib-payload/ib-payload-js/src/main/java/com/intellibucket/lib/payload/outbox/ProcessNameReferences.java
> +    String getProcessName();
Ehiyac yoxdur

2024-03-05 22:56 UTC, royalhsyn commented
Okay, Kommentleri oxudum ,duzelis edib tekrar push edeceyem

2024-03-07 10:27 UTC, l00pss commented on job-seeker-service/js-domain/js-domain-presentation/src/main/java/az/rock/flyjob/js/domain/presentation/ports/output/publisher/AbstractInterestMessagePublisher.java
> +public interface AbstractInterestMessagePublisher<S extends AbstractDomainEvent> extends AbstractMessagePublisher<S> {
Beli zehmet olmasa

2024-03-07 10:27 UTC, l00pss commented on library/ib-payload/ib-payload-js/src/main/java/com/intellibucket/lib/payload/outbox/ProcessNameReferences.java
> +    String getProcessName();
Bunuda silersiz zehmet olmasa

2024-03-07 10:29 UTC, l00pss approved these changes

2024-03-07 10:29 UTC, merged